### ISSUE TITLE
UID获取服务器疑似无法使用代理服务器访问

### ISSUE THREAD

**Issue by kuilb** [ayyayyayy2002/BilibiliAutoReport#1]
版本4.0.0
环境WIN11专业版，未安装pycharm，使用路由器代理香港IP
运行GetUid.bat后如图所示
![image](https://github.com/user-attachments/assets/cba877a9-e41b-4c0e-9e40-267b6e0dba16)
关闭路由器代理并重新运行脚本后恢复正常
![image](https://github.com/user-attachments/assets/450d9c8c-c10d-47f8-9672-0e61898780e8)

**Comment by ayyayyayy2002** [comment]
> 版本4.0.0 环境WIN11专业版，未安装pycharm，使用路由器代理香港IP 运行GetUid.bat后如图所示 ![image](https://private-user-images.githubusercontent.com/58779114/386282417-cba877a9-e41b-4c0e-9e40-267b6e0dba16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDI2MzQsIm5iZiI6MTczMTYwMjMzNCwicGF0aCI6Ii81ODc3OTExNC8zODYyODI0MTctY2JhODc3YTktZTQxYi00YzBlLTllNDAtMjY3YjZlMGRiYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE2Mzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlOGQ4NTk2M2JjYmVmODgzZjA3NTI0MWMxOTJmYmI3N2M5MTRmZGEwNjQ3ZTA5MDJlOTc4NjYyNmMxMDBlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UJVpIxzUAm1oxNNF6PZn8vPxnr1SKfY57Baix7FUFpk) 关闭路由器代理并重新运行脚本后恢复正常 ![image](https://private-user-images.githubusercontent.com/58779114/386285080-450d9c8c-c10d-47f8-9672-0e61898780e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDI2MzQsIm5iZiI6MTczMTYwMjMzNCwicGF0aCI6Ii81ODc3OTExNC8zODYyODUwODAtNDUwZDljOGMtYzEwZC00N2Y4LTk2NzItMGU2MTg5ODc4MGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE2Mzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTFiYjU3OTQxNGIzNThjOWRmMWE1NDlhMTQzNWMyZmEzMTllMmQwNDIzYWI4YzY5MmRhM2UzNTAzNGYyMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pwAzteLG-xZYI9ABA5EDNpIlzVEXdFijGY3p968bcKs)
 
raw.kkgithub.com是国内的一个GitHub加速地址，直接换成本仓库的文件地址就行，云端文件无法下载可以使用本地的文件，按照代码对应的位置创建就行
